name: "Test"

on:
  push:
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [labeled]

jobs:
  tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Configure prerequisites
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.17"
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
 
      # Generate mocks
      - name: Generate mocks
        run: go generate ./...

      # Run gosec
      - name: Install gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        if: runner.os == 'Linux'
      - name: Run gosec
        run: gosec ./...
        if: runner.os == 'Linux'

      # Lint
      - name: Lint
        run: go vet ./...
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1

      # Run tests
      - name: Tests
        run: go test ./... -v -race -timeout 0 -cover -coverprofile=covprofile -covermode=atomic
        env:
          JF_URL: ${{ secrets.FROGBOT_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}

      # Generate code coverage
      - name: Send coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: runner.os == 'Linux'

  # Build and run frogbot current changes for visual sanity check.
  sanity-pull-request:
    needs: tests
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Frogbot
        run: buildscripts/build.sh
      - name: Scan
        env:
          JF_URL: ${{ secrets.FROGBOT_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ github.base_ref }}
          JF_GIT_PULL_REQUEST_ID: ${{ github.event.number }}
          JF_GIT_PROVIDER: "github"
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_REPO: ${{ github.event.repository.name }}
        run: ./frogbot scan-pull-request